"""empty message

Revision ID: 3a213e0020b0
Revises: c3494067301b
Create Date: 2020-02-11 15:36:02.795701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a213e0020b0'
down_revision = 'c3494067301b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Party',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('part_symbol', sa.String(length=180), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Politician',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('image_link', sa.String(length=180), nullable=True),
    sa.Column('famous_posts', sa.String(length=500), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['Party.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('Drink')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Drink',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Drink_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('tagline', sa.VARCHAR(length=180), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Drink_pkey'),
    sa.UniqueConstraint('title', name='Drink_title_key')
    )
    op.drop_table('Politician')
    op.drop_table('Party')
    # ### end Alembic commands ###
