"""empty message

Revision ID: 5497d0e858aa
Revises: 6508a0ffa068
Create Date: 2020-02-11 16:00:24.031862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5497d0e858aa'
down_revision = '6508a0ffa068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Party', sa.Column('party_symbol', sa.String(length=180), nullable=True))
    op.drop_column('Party', 'part_symbol')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Party', sa.Column('part_symbol', sa.VARCHAR(length=180), autoincrement=False, nullable=True))
    op.drop_column('Party', 'party_symbol')
    # ### end Alembic commands ###
