"""empty message

Revision ID: 6508a0ffa068
Revises: 3a213e0020b0
Create Date: 2020-02-11 15:53:53.875806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6508a0ffa068'
down_revision = '3a213e0020b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.Column('topic', sa.String(length=180), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['Party.id'], ),
    sa.ForeignKeyConstraint(['politician_id'], ['Politician.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('Politician_name_key', 'Politician', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Politician_name_key', 'Politician', ['name'])
    op.drop_table('Quotes')
    # ### end Alembic commands ###
